//
// Created by Hans Johnson on 2026-02-14.
//

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include <iostream>
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkBinaryThresholdImageFilter.h"


int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  // Thresholding example from ITK examples site:
//  if (argc != 5)
//  {
//    std::cerr << "Usage: " << std::endl;
//    std::cerr << argv[0];
//    std::cerr << " <InputFileName> <OutputFileName> <Lower Threshold> <Upper Threshold>";
//    std::cerr << std::endl;
//    return EXIT_FAILURE;
//  }//test

  //const char * inputFileName = argv[1];
  //const char * outputFileName = argv[2];

  constexpr unsigned int Dimension = 3;

  using PixelType = signed short;
  using ImageType = itk::Image<PixelType, Dimension>;

  const auto inputImage = itk::ReadImage<ImageType>(inputVolume);


  using FilterType = itk::BinaryThresholdImageFilter<ImageType, ImageType>;
  auto filter = FilterType::New();

  filter->SetInput(inputImage);
  filter->SetLowerThreshold(lowThreshold);
  filter->SetUpperThreshold(highThreshold);
  filter->SetOutsideValue(outsideValue);
  filter->SetInsideValue(insideValue);

  try
  {
    itk::WriteImage(filter->GetOutput(), outputVolume);
  }
  catch (const itk::ExceptionObject & error)
  {
    std::cerr << "Error: " << error << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
