//
// Created by Hans Johnson on 2026-02-14.
//

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include <iostream>

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

//  std::cout << "The number of iterations is: " << numberOfIterations
//            << std::endl;
//  std::cout << "The input volume is: " << inputVolume << std::endl;
//  std::cout << "The output volume is: " << outputVolume << std::endl;
  return EXIT_SUCCESS;
}
