//
// Created by ocx on 3/10/26.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include <iostream>
#include "itkSmoothingRecursiveGaussianImageFilter.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"


int main (int argc, char * argv[])
{
  PARSE_ARGS;

  constexpr unsigned int Dimension = 3;

  using PixelType = unsigned char;
  using ImageType = itk::Image<PixelType, Dimension>;

  const auto inputImage = itk::ReadImage<ImageType>(inputVolume);

  using FilterType = itk::SmoothingRecursiveGaussianImageFilter<ImageType, ImageType>;
  auto smoothFilter = FilterType::New();

  smoothFilter->SetSigma(sigma1);
  smoothFilter->SetInput(inputImage);

  try
  {
    itk::WriteImage(smoothFilter->GetOutput(), outputVolume);
  }
  catch (const itk::ExceptionObject & error)
  {
    std::cerr << "Error: " << error << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
