//
// Created by ocx on 3/10/26.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include <iostream>
#include "itkSmoothingRecursiveGaussianImageFilter.h"
#include "itkSubtractImageFilter.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"


int main (int argc, char * argv[])
{
  PARSE_ARGS;

  constexpr unsigned int Dimension = 3;

  using PixelType = unsigned char;
  using ImageType = itk::Image<PixelType, Dimension>;

  const auto inputImage = itk::ReadImage<ImageType>(inputVolume);

  using SmoothFilterType = itk::SmoothingRecursiveGaussianImageFilter<ImageType, ImageType>;
  using SubtractFilterType = itk::SubtractImageFilter<ImageType, ImageType>;

  try
  {
    auto smoothFilter1 = SmoothFilterType::New();
    smoothFilter1->SetSigma(sigma1);
    smoothFilter1->SetInput(inputImage);

    auto smoothFilter2 = SmoothFilterType::New();
    smoothFilter2->SetSigma(sigma2);
    smoothFilter2->SetInput(inputImage);

    auto subtractFilter = SubtractFilterType::New();
    subtractFilter->SetInput1(smoothFilter1->GetOutput());
    subtractFilter->SetInput2(smoothFilter2->GetOutput());

    itk::WriteImage(subtractFilter->GetOutput(), outputVolume);
  }
  catch (const itk::ExceptionObject & error)
  {
    std::cerr << "Error: " << error << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
