//
// Created by ocx on 3/10/26.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include <iostream>
#include "itkSmoothingRecursiveGaussianImageFilter.h"
#include "itkSubtractImageFilter.h"
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkRescaleIntensityImageFilter.h"
#include "itkCastImageFilter.h"

// test


int main (int argc, char * argv[])
{
  PARSE_ARGS;

  if (sigma1 == sigma2) {
    std::cerr << "Error: sigma1 and sigma2 must be different." << std::endl;
    return EXIT_FAILURE;
  }

  constexpr unsigned int Dimension = 3;

  using PixelType = float;
  using OutputPixelType = unsigned char;
  using ImageType = itk::Image<PixelType, Dimension>;
  using OutputImageType = itk::Image<OutputPixelType, Dimension>;

  const auto inputImage = itk::ReadImage<ImageType>(inputVolume);

  using SmoothFilterType = itk::SmoothingRecursiveGaussianImageFilter<ImageType, ImageType>;
  using SubtractFilterType = itk::SubtractImageFilter<ImageType, ImageType>;

  try
  {
    auto smoothFilter1 = SmoothFilterType::New();
    smoothFilter1->SetSigma(sigma1);
    smoothFilter1->SetInput(inputImage);

    auto smoothFilter2 = SmoothFilterType::New();
    smoothFilter2->SetSigma(sigma2);
    smoothFilter2->SetInput(inputImage);

    auto subtractFilter = SubtractFilterType::New();
    subtractFilter->SetInput1(smoothFilter1->GetOutput());
    subtractFilter->SetInput2(smoothFilter2->GetOutput());

    // Make sure to rescale

    using FilterType = itk::RescaleIntensityImageFilter<ImageType, ImageType>;
    auto rescaleFilter = FilterType::New();

    rescaleFilter->SetInput(subtractFilter->GetOutput());
    rescaleFilter->SetOutputMinimum(0);
    rescaleFilter->SetOutputMaximum(255);

    // Next, I need to make sure output image is unsigned char as described in homework description

    using CastFilterType = itk::CastImageFilter<ImageType, OutputImageType>;
    auto castFilter = CastFilterType::New();

    castFilter->SetInput(rescaleFilter->GetOutput());

    itk::WriteImage(castFilter->GetOutput(), outputVolume);
  }
  catch (const itk::ExceptionObject & error)
  {
    std::cerr << "Error: " << error << std::endl;
    return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
